version: "3"
services:
  web:
    build:
      context: ./react-web
      dockerfile: Dockerfile
    ports: 
      - "5173:5173"
    volumes:
      - /usr/src/app/node_modules
      - ./react-web:/usr/src/app
  admin:
    build:
      context: ./react-admin
      dockerfile: Dockerfile
    ports: 
      - "5174:5174"
    volumes:
      - /usr/src/app/node_modules
      - ./react-admin:/usr/src/app
  server:
    build:
      context: ./API-server
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - /usr/src/app/node_modules
      - ./API-server:/usr/src/app
  mongodb:
    image: mongo:latest
    ports:
    - "27017:27017"
    volumes:
    - mongodb_data:/data/db
volumes:
  mongodb_data:
