name: readingguide

services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_PROXY_TARGET=http://server:3000
    volumes:
      - readingguide_web_modules:/usr/src/app/node_modules
      - ./client:/usr/src/app
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    depends_on:
      - mongodb
    volumes:
      - readingguide_server_modules:/usr/src/app/node_modules
      - ./server:/usr/src/app
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - readingguide_mongodb:/data/db
volumes:
  readingguide_web_modules:
  readingguide_server_modules:
  readingguide_mongodb:
