version: "3"
services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports: 
      - "5173:5173"
    volumes:
      - /usr/src/app/node_modules
      - ./client:/usr/src/app
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - /usr/src/app/node_modules
      - ./server:/usr/src/app
  mongodb:
    image: mongo:latest
    ports:
    - "27017:27017"
    volumes:
    - mongodb_data:/data/db
volumes:
  mongodb_data:
