/**
 * The `Feedback` interface represents a user's feedback within the application.
 * It includes both the textual feedback provided by the user and the grades associated with it,
 * either calculated automatically (calculatedAviGrade) or provided by the user (feedbackAviGrade).
 * Additionally, it tracks the review status to manage the feedback processing workflow.
 *
 * Properties:
 * - `_id`: A unique identifier for the feedback item, typically generated by the database.
 * - `text`: The main content of the feedback provided by the user.
 * - `feedbackAviGrade`: The grade assigned by the user, reflecting their subjective evaluation.
 * - `calculatedAviGrade`: The grade calculated by the system, based on objective criteria or algorithms.
 * - `status`: The current review status of the feedback, which helps in categorizing and processing feedback items.
 * 
 * The `FeedbackReviewStatus` type used for the `status` property should be an enumeration
 * that lists all possible states of feedback review (e.g., Pending, Reviewed, Rejected).
 */

import { FeedbackReviewStatus, AviGrade } from "./enums";

export interface Feedback {
    _id: string;
    text: string;
    feedbackAviGrade: AviGrade;
    calculatedAviGrade: AviGrade;
    status: FeedbackReviewStatus;
};
